#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "OverlaneNetTypes.h"
#include "ArcadeHandlingComponent.generated.h"

UCLASS(ClassGroup = (Vehicle), meta = (BlueprintSpawnableComponent))
class OVERLANE_API UArcadeHandlingComponent : public UActorComponent
{
    GENERATED_BODY()

public:
    UArcadeHandlingComponent();

    void SetThrottleInput(float Value);
    void SetBrakeInput(float Value);
    void SetSteeringInput(float Value);
    void SetBoostInput(bool bEnabled);
    /**
     * @param bRefillBoost  false for in-race recovery. Refilling there made R a
     *                      free full turbo bar with no cooldown, which on the
     *                      host ran server-side and was simply an exploit.
     */
    void ResetState(bool bRefillBoost = true);
    float GetSpeedKph() const;
    float GetSpeedRatio() const;

    /**
     * Signed forward speed in cm/s. The bot's follow and time-to-collision maths
     * works in the same units the traffic system uses; GetSpeedKph is a display
     * conversion and GetSpeedRatio divides by MaxBoostSpeed, so neither fits.
     */
    float GetForwardSpeed() const { return CurrentSpeed; }

    /** Cosmetic only: wheel steer angle and body roll are driven from this. */
    float GetSteeringInput() const { return SteeringInput; }

    /** Scales top speed and acceleration. The AI rival's difficulty lever. */
    void SetPerformanceScale(float InScale);

    /**
     * Advance the vehicle by exactly one fixed step from one input command.
     *
     * This is the whole simulation and the only thing that may touch sim state.
     * It is deliberately a pure function of (state, command, FixedDt): server,
     * owning-client prediction and replay all call it, and all three must agree.
     */
    void SimulateStep(const FOverlaneInputCommand& Command, float FixedDt, EOverlaneStepMode Mode);

    FOverlaneVehicleSimState GetSimState() const;

    /** Overwrites simulation state and teleports the pawn. Used by reconciliation. */
    void SetSimState(const FOverlaneVehicleSimState& InState);

    uint8 GetCollisionEventCount() const { return CollisionEventCount; }

    /**
     * Feed one command from a remote client's batch into the jitter queue.
     *
     * Once anything is enqueued this component is command-driven and stops
     * sampling its cached scalars, so a client that goes quiet repeats its last
     * command rather than inheriting whatever was last written locally.
     */
    void EnqueueCommand(const FOverlaneInputCommand& Command);

    uint16 GetLastConsumedSequence() const { return LastConsumedSequence; }
    bool IsInputStarved() const { return bInputStarved; }
    void ClearPendingCommands();
    float GetCollisionCutCooldownDuration() const { return CollisionCutCooldownDuration; }

    /** True once if the queue overflowed and the command stream jumped. */
    bool ConsumePendingForceSnap();

    // --- Client-side prediction ---------------------------------------------

    /** True when this machine is predicting rather than echoing the server. */
    bool IsPredictingHere() const;

    /** Drain commands generated by prediction, for the controller to send. */
    void DrainPredictedOutbox(TArray<FOverlaneInputCommand>& OutCommands);

    /** The predicted move stored for this sequence, or null if it has aged out. */
    const FOverlanePredictedMove* FindPredictedMove(uint16 Sequence) const;

    /** Number of predicted moves newer than this sequence. */
    int32 CountMovesAfter(uint16 Sequence) const;

    /** Wipe the prediction history and restart from this state. */
    void ResetPredictionTo(uint16 Sequence, const FOverlaneVehicleSimState& State);
    float GetBoostChargeRatio() const { return BoostCharge; }
    bool IsBoostActive() const { return bBoostActive; }

    virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;

protected:
    UPROPERTY(EditAnywhere, Category = "Arcade Handling|Speed", meta = (ClampMin = "1.0"))
    float MaxForwardSpeed = 5000.0f;

    UPROPERTY(EditAnywhere, Category = "Arcade Handling|Speed", meta = (ClampMin = "1.0"))
    float MaxReverseSpeed = 1200.0f;

    UPROPERTY(EditAnywhere, Category = "Arcade Handling|Speed", meta = (ClampMin = "1.0"))
    float Acceleration = 2800.0f;

    UPROPERTY(EditAnywhere, Category = "Arcade Handling|Speed", meta = (ClampMin = "1.0"))
    float BrakingDeceleration = 7200.0f;

    UPROPERTY(EditAnywhere, Category = "Arcade Handling|Speed", meta = (ClampMin = "1.0"))
    float CoastDeceleration = 550.0f;

    UPROPERTY(EditAnywhere, Category = "Arcade Handling|Boost", meta = (ClampMin = "1.0"))
    float MaxBoostSpeed = 6800.0f;

    UPROPERTY(EditAnywhere, Category = "Arcade Handling|Boost", meta = (ClampMin = "1.0"))
    float BoostAcceleration = 4200.0f;

    UPROPERTY(EditAnywhere, Category = "Arcade Handling|Boost", meta = (ClampMin = "0.0"))
    float BoostMinimumSpeed = 850.0f;

    UPROPERTY(EditAnywhere, Category = "Arcade Handling|Boost", meta = (ClampMin = "0.0"))
    float BoostDrainPerSecond = 0.42f;

    UPROPERTY(EditAnywhere, Category = "Arcade Handling|Boost", meta = (ClampMin = "0.0"))
    float BoostRechargePerSecond = 0.18f;

    UPROPERTY(EditAnywhere, Category = "Arcade Handling|Steering", meta = (ClampMin = "1.0"))
    float SteeringRateDegreesPerSecond = 105.0f;

    UPROPERTY(EditAnywhere, Category = "Arcade Handling|Steering", meta = (ClampMin = "0.0", ClampMax = "1.0"))
    float HighSpeedSteeringMultiplier = 0.32f;

    UPROPERTY(EditAnywhere, Category = "Arcade Handling|Collision", meta = (ClampMin = "0.0", ClampMax = "1.0"))
    float CollisionSpeedMultiplier = 0.45f;

    /**
     * Minimum time between two speed cuts.
     *
     * Without it the cut fired once per rendered frame, so a 30 ms scrape cost
     * four cuts at 144 fps (0.45^4 = 0.041x speed) but only two at 60 fps
     * (0.20x) -- the same contact was ~2.4x harsher on a faster machine. With
     * the cooldown a scrape costs exactly one cut at any frame rate, which also
     * turns the cut into a countable discrete event the network layer can match.
     */
    UPROPERTY(EditAnywhere, Category = "Arcade Handling|Collision", meta = (ClampMin = "0.0"))
    float CollisionCutCooldownDuration = 0.12f;

    UPROPERTY(EditAnywhere, Category = "Arcade Handling|Speed", meta = (ClampMin = "0.5", ClampMax = "1.15"))
    float PerformanceScale = 1.0f;

private:
    bool IsDrivingAllowedHere() const;
    bool ShouldSimulateHere() const;

    /** One command per fixed step, from the queue when driven remotely. */
    bool ConsumeNextCommand(FOverlaneInputCommand& OutCommand);

    /** Server-side jitter queue for a remotely driven pawn. */
    TArray<FOverlaneInputCommand> PendingCommands;
    FOverlaneInputCommand LastConsumedCommand;
    uint16 LastConsumedSequence = 0;

    /** Steps simulated from a repeated command, owed back when input resumes. */
    int32 StarveDebt = 0;

    /** 0.5 s of repeats; past this, hold rather than keep guessing. */
    static constexpr int32 MaxStarveDebtSteps = 30;

    /** Queue depth kept as jitter absorption when trimming an overflow. */
    static constexpr int32 ServerBufferTarget = 2;

    bool bCommandDriven = false;
    bool bInputStarved = false;
    bool bPendingForceSnap = false;

    /** Read once per frame: never call GetValueOnGameThread inside the step loop. */
    bool bPredictEnabledThisFrame = false;

    void StorePredictedMove(const FOverlaneInputCommand& Command, bool bBlocked);

    /** Indexed by Sequence % size, with the stored sequence checked on lookup. */
    TArray<FOverlanePredictedMove> MoveRing;

    /** Generated on the predicting client, drained by the controller to send. */
    TArray<FOverlaneInputCommand> PredictedOutbox;

    uint16 NextPredictedSequence = 1;

    /** Set by the last SimulateStep: did its swept move hit anything. */
    bool bLastStepBlocked = false;

    float ThrottleInput = 0.0f;
    float BrakeInput = 0.0f;
    float SteeringInput = 0.0f;
    bool bBoostRequested = false;
    bool bBoostActive = false;
    float BoostCharge = 1.0f;
    float CurrentSpeed = 0.0f;

    /** Leftover real time not yet consumed by a fixed step. */
    float StepAccumulator = 0.0f;
    float CollisionCutCooldown = 0.0f;
    uint8 CollisionEventCount = 0;

    /** Sequence stamped on locally generated commands until the net layer owns it. */
    uint16 LocalCommandSequence = 0;
};
